/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../../../../index";

/**
 * @example
 *     {
 *         attachments: [{
 *                 url: "https://toretto.family/coronas.gif"
 *             }],
 *         body: "Thought you could leave without saying goodbye?",
 *         conversation: {
 *             contact: {
 *                 first_name: "Dominic",
 *                 last_name: "Toretto",
 *                 phone_number: "+18015551234"
 *             }
 *         }
 *     }
 */
export interface MessageRequest {
    attachments?: Surge.AttachmentParams[];
    /** The message body. */
    body?: string;
    conversation: Surge.MessageConversationParams;
    /** An optional datetime for scheduling message up to a couple of months in the future. */
    send_at?: string;
}
