/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../../../../index";

/**
 * @example
 *     {
 *         attachments: [{
 *                 url: "https://toretto.family/coronas.gif"
 *             }],
 *         body: "Thought you could leave without saying goodbye?",
 *         conversation: {
 *             contact: {
 *                 first_name: "Dominic",
 *                 id: "ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
 *                 last_name: "Toretto",
 *                 phone_number: "+18015551234"
 *             },
 *             id: "cnv_01j9e0dgmdfkj86c877ws0znae"
 *         }
 *     }
 */
export interface MessageRequest {
    attachments?: Surge.AttachmentParams[];
    /** The message body. */
    body?: string;
    conversation: Surge.MessageConversationParams;
}
