/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Splitit from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Messages {
    interface Options {
        environment?: core.Supplier<environments.SplititEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        /** Override the Surge-Account header */
        surgeAccount?: core.Supplier<string | undefined>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the Surge-Account header */
        surgeAccount?: string | undefined;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Messages {
    constructor(protected readonly _options: Messages.Options) {}

    /**
     * Sends a Message.
     *
     * @param {Splitit.MessageRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.messages.create({
     *         attachments: [{
     *                 url: "https://toretto.family/coronas.gif"
     *             }],
     *         body: "Thought you could leave without saying goodbye?",
     *         conversation: {
     *             contact: {
     *                 first_name: "Dominic",
     *                 id: "ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
     *                 last_name: "Toretto",
     *                 phone_number: "+18015551234"
     *             },
     *             id: "cnv_01j9e0dgmdfkj86c877ws0znae"
     *         }
     *     })
     */
    public create(
        request: Splitit.MessageRequest,
        requestOptions?: Messages.RequestOptions
    ): core.APIPromise<Splitit.MessageResponse> {
        return core.APIPromise.from(
            (async () => {
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ?? environments.SplititEnvironment.Default,
                        "messages"
                    ),
                    method: "POST",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        "Surge-Account":
                            (await core.Supplier.get(this._options.surgeAccount)) != null
                                ? await core.Supplier.get(this._options.surgeAccount)
                                : undefined,
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "surge",
                        "X-Fern-SDK-Version": "0.24.7",
                        "User-Agent": "surge/0.24.7",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    body: request,
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: _response.body as Splitit.MessageResponse,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.SplititError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.SplititError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.SplititTimeoutError("Timeout exceeded when calling POST /messages.");
                    case "unknown":
                        throw new errors.SplititError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
