/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Surge from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Messages {
    export interface Options {
        environment?: core.Supplier<environments.SurgeEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Messages {
    constructor(protected readonly _options: Messages.Options) {}

    /**
     * Sends a Message.
     *
     * @param {string} accountId - The account for which the message should be sent.
     * @param {Surge.MessageRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.messages.send("acct_01j9a43avnfqzbjfch6pygv1td", {
     *         attachments: [{
     *                 url: "https://toretto.family/coronas.gif"
     *             }],
     *         body: "Thought you could leave without saying goodbye?",
     *         conversation: {
     *             contact: {
     *                 first_name: "Dominic",
     *                 last_name: "Toretto",
     *                 phone_number: "+18015551234"
     *             }
     *         }
     *     })
     */
    public send(
        accountId: string,
        request: Surge.MessageRequest,
        requestOptions?: Messages.RequestOptions,
    ): core.HttpResponsePromise<Surge.MessageResponse> {
        return core.HttpResponsePromise.fromPromise(this.__send(accountId, request, requestOptions));
    }

    private async __send(
        accountId: string,
        request: Surge.MessageRequest,
        requestOptions?: Messages.RequestOptions,
    ): Promise<core.WithRawResponse<Surge.MessageResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SurgeEnvironment.Default,
                `accounts/${encodeURIComponent(accountId)}/messages`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@surgeapi/node",
                "X-Fern-SDK-Version": "0.25.7",
                "User-Agent": "@surgeapi/node/0.25.7",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Surge.MessageResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SurgeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SurgeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SurgeTimeoutError(
                    "Timeout exceeded when calling POST /accounts/{account_id}/messages.",
                );
            case "unknown":
                throw new errors.SurgeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
