/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Surge from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Accounts {
    export interface Options {
        environment?: core.Supplier<environments.SurgeEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Accounts {
    constructor(protected readonly _options: Accounts.Options) {}

    /**
     * Creates a new Account within the calling Platform.
     *
     * @param {Surge.CreateAccountRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.accounts.create({
     *         name: "D\u00B7T Precision Auto Shop",
     *         time_zone: "America/Los_Angeles"
     *     })
     */
    public async create(
        request: Surge.CreateAccountRequest,
        requestOptions?: Accounts.RequestOptions,
    ): Promise<Surge.AccountResponse> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SurgeEnvironment.Default,
                "accounts",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@surgeapi/node",
                "X-Fern-SDK-Version": "0.25.5",
                "User-Agent": "@surgeapi/node/0.25.5",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as Surge.AccountResponse;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SurgeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SurgeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SurgeTimeoutError("Timeout exceeded when calling POST /accounts.");
            case "unknown":
                throw new errors.SurgeError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Updates an Account
     *
     * @param {string} id -
     * @param {Surge.UpdateAccountRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.accounts.update("acct_01jpqjvfg9enpt7pyxd60pcmxj", {
     *         name: "D\u00B7T Precision Auto Shop",
     *         time_zone: "America/Los_Angeles"
     *     })
     */
    public async update(
        id: string,
        request: Surge.UpdateAccountRequest = {},
        requestOptions?: Accounts.RequestOptions,
    ): Promise<Surge.AccountResponse> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SurgeEnvironment.Default,
                `accounts/${encodeURIComponent(id)}`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@surgeapi/node",
                "X-Fern-SDK-Version": "0.25.5",
                "User-Agent": "@surgeapi/node/0.25.5",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as Surge.AccountResponse;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SurgeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SurgeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SurgeTimeoutError("Timeout exceeded when calling PATCH /accounts/{id}.");
            case "unknown":
                throw new errors.SurgeError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
