/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         code: "123456"
 *     }
 */
export interface VerificationCheckRequest {
    /** The Verification code that was received. */
    code: string;
}
