/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         phone_number: "+18015551234"
 *     }
 */
export interface VerificationRequest {
    /** The phone number to be verified. In E.164 format. */
    phone_number: string;
}
