/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "D\u00B7T Precision Auto Shop",
 *         time_zone: "America/Los_Angeles"
 *     }
 */
export interface CreateAccountRequest {
    /** The name of the account */
    name: string;
    /** The time zone for the account */
    time_zone?: string;
}
