/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Surge from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Contacts {
    export interface Options {
        environment?: core.Supplier<environments.SurgeEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Contacts {
    constructor(protected readonly _options: Contacts.Options) {}

    /**
     * Creates a new Contact object.
     *
     * @param {string} accountId - The account for which the contact should be created.
     * @param {Surge.ContactRequest} request
     * @param {Contacts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contacts.create("acct_01j9a43avnfqzbjfch6pygv1td", {
     *         email: "dom@toretto.family",
     *         first_name: "Dominic",
     *         last_name: "Toretto",
     *         metadata: {
     *             "car": "1970 Dodge Charger R/T"
     *         },
     *         phone_number: "+18015551234"
     *     })
     */
    public create(
        accountId: string,
        request: Surge.ContactRequest,
        requestOptions?: Contacts.RequestOptions,
    ): core.HttpResponsePromise<Surge.ContactResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(accountId, request, requestOptions));
    }

    private async __create(
        accountId: string,
        request: Surge.ContactRequest,
        requestOptions?: Contacts.RequestOptions,
    ): Promise<core.WithRawResponse<Surge.ContactResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SurgeEnvironment.Default,
                `accounts/${encodeURIComponent(accountId)}/contacts`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@surgeapi/node",
                "X-Fern-SDK-Version": "0.25.6",
                "User-Agent": "@surgeapi/node/0.25.6",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Surge.ContactResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SurgeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SurgeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SurgeTimeoutError(
                    "Timeout exceeded when calling POST /accounts/{account_id}/contacts.",
                );
            case "unknown":
                throw new errors.SurgeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieves a Contact object.
     *
     * @param {string} id -
     * @param {Contacts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contacts.getContact("ctc_01j9dy8mdzfn3r0e8x1tbdrdrf")
     */
    public getContact(
        id: string,
        requestOptions?: Contacts.RequestOptions,
    ): core.HttpResponsePromise<Surge.ContactResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getContact(id, requestOptions));
    }

    private async __getContact(
        id: string,
        requestOptions?: Contacts.RequestOptions,
    ): Promise<core.WithRawResponse<Surge.ContactResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SurgeEnvironment.Default,
                `contacts/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@surgeapi/node",
                "X-Fern-SDK-Version": "0.25.6",
                "User-Agent": "@surgeapi/node/0.25.6",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Surge.ContactResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SurgeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SurgeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SurgeTimeoutError("Timeout exceeded when calling GET /contacts/{id}.");
            case "unknown":
                throw new errors.SurgeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Updates the specified contact by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
     *
     * @param {string} id -
     * @param {Surge.ContactRequest} request
     * @param {Contacts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contacts.update("ctc_01j9dy8mdzfn3r0e8x1tbdrdrf", {
     *         email: "dom@toretto.family",
     *         first_name: "Dominic",
     *         last_name: "Toretto",
     *         metadata: {
     *             "car": "1970 Dodge Charger R/T"
     *         },
     *         phone_number: "+18015551234"
     *     })
     */
    public update(
        id: string,
        request: Surge.ContactRequest,
        requestOptions?: Contacts.RequestOptions,
    ): core.HttpResponsePromise<Surge.ContactResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(id, request, requestOptions));
    }

    private async __update(
        id: string,
        request: Surge.ContactRequest,
        requestOptions?: Contacts.RequestOptions,
    ): Promise<core.WithRawResponse<Surge.ContactResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SurgeEnvironment.Default,
                `contacts/${encodeURIComponent(id)}`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@surgeapi/node",
                "X-Fern-SDK-Version": "0.25.6",
                "User-Agent": "@surgeapi/node/0.25.6",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Surge.ContactResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SurgeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SurgeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SurgeTimeoutError("Timeout exceeded when calling PATCH /contacts/{id}.");
            case "unknown":
                throw new errors.SurgeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
