/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Surge from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Contacts {
    interface Options {
        environment?: core.Supplier<environments.SurgeEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        /** Override the Surge-Account header */
        surgeAccount?: core.Supplier<string | undefined>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the Surge-Account header */
        surgeAccount?: string | undefined;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Contacts {
    constructor(protected readonly _options: Contacts.Options) {}

    /**
     * Creates a new Contact object.
     *
     * @param {Surge.ContactRequest} request
     * @param {Contacts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contacts.create({
     *         first_name: "Dominic",
     *         last_name: "Toretto",
     *         phone_number: "+18015551234"
     *     })
     */
    public create(
        request: Surge.ContactRequest,
        requestOptions?: Contacts.RequestOptions
    ): core.APIPromise<Surge.ContactResponse> {
        return core.APIPromise.from(
            (async () => {
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ?? environments.SurgeEnvironment.Default,
                        "contacts"
                    ),
                    method: "POST",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        "Surge-Account":
                            (await core.Supplier.get(this._options.surgeAccount)) != null
                                ? await core.Supplier.get(this._options.surgeAccount)
                                : undefined,
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "surge",
                        "X-Fern-SDK-Version": "0.24.7",
                        "User-Agent": "surge/0.24.7",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    body: request,
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: _response.body as Surge.ContactResponse,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.SurgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.SurgeError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.SurgeTimeoutError("Timeout exceeded when calling POST /contacts.");
                    case "unknown":
                        throw new errors.SurgeError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * Retrieves a Contact object.
     *
     * @param {string} id -
     * @param {Contacts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contacts.show("ctc_01j9dy8mdzfn3r0e8x1tbdrdrf")
     */
    public show(id: string, requestOptions?: Contacts.RequestOptions): core.APIPromise<Surge.ContactResponse> {
        return core.APIPromise.from(
            (async () => {
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ?? environments.SurgeEnvironment.Default,
                        `contacts/${encodeURIComponent(id)}`
                    ),
                    method: "GET",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        "Surge-Account":
                            (await core.Supplier.get(this._options.surgeAccount)) != null
                                ? await core.Supplier.get(this._options.surgeAccount)
                                : undefined,
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "surge",
                        "X-Fern-SDK-Version": "0.24.7",
                        "User-Agent": "surge/0.24.7",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: _response.body as Surge.ContactResponse,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.SurgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.SurgeError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.SurgeTimeoutError("Timeout exceeded when calling GET /contacts/{id}.");
                    case "unknown":
                        throw new errors.SurgeError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * Updates the specified contact by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
     *
     * @param {string} id -
     * @param {Contacts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contacts.update("ctc_01j9dy8mdzfn3r0e8x1tbdrdrf")
     */
    public update(id: string, requestOptions?: Contacts.RequestOptions): core.APIPromise<Surge.ContactResponse> {
        return core.APIPromise.from(
            (async () => {
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ?? environments.SurgeEnvironment.Default,
                        `contacts/${encodeURIComponent(id)}`
                    ),
                    method: "PUT",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        "Surge-Account":
                            (await core.Supplier.get(this._options.surgeAccount)) != null
                                ? await core.Supplier.get(this._options.surgeAccount)
                                : undefined,
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "surge",
                        "X-Fern-SDK-Version": "0.24.7",
                        "User-Agent": "surge/0.24.7",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: _response.body as Surge.ContactResponse,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.SurgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.SurgeError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.SurgeTimeoutError("Timeout exceeded when calling PUT /contacts/{id}.");
                    case "unknown":
                        throw new errors.SurgeError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
