/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response containing account information
 */
export interface AccountResponse {
    /** The account ID */
    id: string;
    /** The name of the account */
    name: string;
    /** The time zone for the account */
    time_zone?: string;
}
