/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response schema for single attachment
 */
export interface AttachmentResponse {
    /** Unique identifier for the object. */
    id?: string;
    /** The type of attachment. */
    type?: string;
    /** The URL of the attachment. */
    url?: string;
}
