/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Params for creating an attachment
 */
export interface AttachmentParams {
    /** The URL of the attachment. */
    url: string;
}
