/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * Response schema for single blast
 */
export interface BlastResponse {
    attachments?: Surge.BlastResponseAttachmentsItem[];
    /** The message body. */
    body?: string;
    /** Unique identifier for the object. */
    id?: string;
    /** Optional name for the blast. */
    name?: string;
    /** When the blast will be or was sent. */
    send_at?: string;
}
