/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response schema for single contact
 */
export interface ContactResponse {
    /** The contact's first name. */
    first_name?: string;
    /** Unique identifier for the object. */
    id?: string;
    /** The contact's last name. */
    last_name?: string;
    /** The contact's phone number in E.164 format. */
    phone_number?: string;
}
