/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the phone number is local, toll-free, or short code
 */
export type ConversationPhoneNumberType = "local" | "toll_free" | "short_code" | "demo";
export const ConversationPhoneNumberType = {
    Local: "local",
    TollFree: "toll_free",
    ShortCode: "short_code",
    Demo: "demo",
} as const;
