/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * This is the phone number tied to the Surge account.
 */
export interface ConversationPhoneNumber {
    /** Unique identifier for the phone number */
    id: string;
    /** The canonical format of the phone number. */
    number: string;
    /** Whether the phone number is local, toll-free, or short code */
    type: Surge.ConversationPhoneNumberType;
}
