/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Splitit from "../index";

/**
 * A conversation with a Contact
 */
export interface Conversation {
    contact: Splitit.Contact;
    /** Unique identifier for the object. */
    id: string;
}
