/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * A conversation with a Contact
 */
export interface Conversation {
    contact: Surge.Contact;
    /** Unique identifier for the object. */
    id: string;
    phone_number?: Surge.ConversationPhoneNumber;
}
