/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * Response schema for single message
 */
export interface MessageResponse {
    attachments?: Surge.AttachmentResponse[];
    /** The message body. */
    body?: string;
    conversation?: Surge.Conversation;
    /** Unique identifier for the object. */
    id?: string;
}
