/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Splitit from "../index";

/**
 * Response schema for single message
 */
export interface MessageResponse {
    attachments?: Splitit.AttachmentResponse[];
    /** The message body. */
    body?: string;
    conversation?: Splitit.Conversation;
    /** Unique identifier for the object. */
    id?: string;
}
