/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * A phone number that can be used to send and receive messages and calls
 */
export interface PhoneNumber {
    /** Unique identifier for the phone number */
    id: string;
    /** The phone number in E.164 format */
    number: string;
    /** Whether the phone number is local, toll-free, or short code */
    type: Surge.PhoneNumberType;
}
