/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the phone number is local, toll-free, or short code
 */
export type PhoneNumberType = "local" | "toll_free";
export const PhoneNumberType = {
    Local: "local",
    TollFree: "toll_free",
} as const;
