/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response schema for single user
 */
export interface UserResponse {
    /** The user's first name. */
    first_name?: string;
    /** Unique identifier for the object. */
    id?: string;
    /** The user's last name. */
    last_name?: string;
    /** Set of key-value pairs that will be stored with the user. */
    metadata?: Record<string, unknown>;
    /** URL of a photo to be used as the user's avatar. */
    photo_url?: string;
}
