/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The result of the code check.
 */
export type VerificationCheckIncorrectResponseResult = "incorrect" | "exhausted" | "expired";
export const VerificationCheckIncorrectResponseResult = {
    Incorrect: "incorrect",
    Exhausted: "exhausted",
    Expired: "expired",
} as const;
