/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * The response returned from checking a Verification code
 */
export interface VerificationCheckResponse {
    /** The result of the code check. */
    result?: Surge.VerificationCheckResponseResult;
    verification?: Surge.Verification;
}
