/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * The response returned from checking a Verification code
 */
export interface VerificationCheckOkResponse {
    /**
     * The result of the code check.
     *
     * This result will affect the status code of the response:
     * - ok: 200
     * - incorrect: 422
     * - exhausted: 422
     * - expired: 422
     * - already_verified: 409
     */
    result?: Surge.VerificationCheckOkResponseResult;
    verification?: Surge.Verification;
}
