/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The result of the code check.
 *
 * This result will affect the status code of the response:
 * - ok: 200
 * - incorrect: 422
 * - exhausted: 422
 * - expired: 422
 * - already_verified: 409
 */
export type VerificationCheckOkResponseResult = "ok" | "incorrect" | "exhausted" | "expired" | "already_verified";
export const VerificationCheckOkResponseResult = {
    Ok: "ok",
    Incorrect: "incorrect",
    Exhausted: "exhausted",
    Expired: "expired",
    AlreadyVerified: "already_verified",
} as const;
