/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * The response returned from checking a Verification code
 */
export interface VerificationCheckIncorrectResponse {
    /** The result of the code check. */
    result?: Surge.VerificationCheckIncorrectResponseResult;
    verification?: Surge.Verification;
}
