/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The result of the code check.
 */
export type VerificationCheckAlreadyVerifiedResponseResult =
    | "ok"
    | "incorrect"
    | "exhausted"
    | "expired"
    | "already_verified";
export const VerificationCheckAlreadyVerifiedResponseResult = {
    Ok: "ok",
    Incorrect: "incorrect",
    Exhausted: "exhausted",
    Expired: "expired",
    AlreadyVerified: "already_verified",
} as const;
