/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../index";

/**
 * A phone number verification
 */
export interface Verification {
    /** The number of times the code has been attempted. */
    attempt_count: number;
    /** Unique identifier for the object. */
    id: string;
    /** The phone number being verified. In E.164 format. */
    phone_number: string;
    /** The current status of the verification. */
    status: Surge.VerificationStatus;
}
