/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current status of the verification.
 */
export type VerificationStatus = "pending" | "verified" | "exhausted" | "expired";

export const VerificationStatus = {
    Pending: "pending",
    Verified: "verified",
    Exhausted: "exhausted",
    Expired: "expired",
} as const;
