/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Splitit from "../index";

/**
 * The response returned from checking a Verification code
 */
export interface VerificationCheckResponse {
    /** The result of the code check. */
    result?: Splitit.VerificationCheckResponseResult;
    verification?: Splitit.Verification;
}
