/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         first_name: "Dominic",
 *         last_name: "Toretto",
 *         phone_number: "+18015551234"
 *     }
 */
export interface ContactRequest {
    /** The contact's first name. */
    first_name?: string;
    /** The contact's last name. */
    last_name?: string;
    /** The contact's phone number in E.164 format. */
    phone_number: string;
}
