/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../../../../index";

/**
 * @example
 *     {
 *         attachments: [{
 *                 url: "https://example.com/image.jpg"
 *             }],
 *         body: "Join us for our grand opening!",
 *         contacts: ["ctc_01j9dy8mdzfn3r0e8x1tbdrdrf"],
 *         name: "Grand Opening Announcement",
 *         segments: ["seg_01j9dy8mdzfn3r0e8x1tbdrdrf"],
 *         send_at: "2024-02-01T15:00:00Z"
 *     }
 */
export interface BlastRequest {
    attachments?: Surge.AttachmentParams[];
    /** The message body. */
    body?: string;
    /** List of contact IDs to send the blast to. */
    contacts?: string[];
    /** Optional name for the blast. */
    name?: string;
    /** List of segment IDs to send the blast to. */
    segments?: string[];
    /** When to send the blast. If not provided, sends immediately. */
    send_at?: string;
}
