/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Surge from "../../../../index";

/**
 * @example
 *     {
 *         attachments: [{
 *                 url: "https://example.com/image.jpg"
 *             }],
 *         body: "Join us for our grand opening!",
 *         name: "Grand Opening Announcement",
 *         send_at: "2024-02-01T15:00:00Z",
 *         to: ["seg_01j9dy8mdzfn3r0e8x1tbdrdrf", "ctc_01j9dy8mdzfn3r0e8x1tbdrdrf", "+18015551234", "+18015555678"]
 *     }
 */
export interface BlastRequest {
    attachments?: Surge.AttachmentParams[];
    /** The message body. */
    body?: string;
    /** Deprecated. Use `to` instead. */
    contacts?: string[];
    /** Optional name for the blast. */
    name?: string;
    /** Deprecated. Use `to` instead. */
    segments?: string[];
    /** When to send the blast. If not provided, sends immediately. */
    send_at?: string;
    /** List of recipients to whom the blast should be sent. This can be a combination of contact IDs, segment IDs, and phone numbers. */
    to?: string[];
}
