/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SurgeEnvironment = {
    Default: "https://api.surge.app",
} as const;

export type SurgeEnvironment = typeof SurgeEnvironment.Default;
