/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SplititEnvironment = {
    Default: "https://api.surgemsg.com",
} as const;

export type SplititEnvironment = typeof SplititEnvironment.Default;
