/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         first_name: "Brian",
 *         last_name: "O'Conner",
 *         metadata: {
 *             "email": "boconner@toretti.family",
 *             "user_id": 1234
 *         },
 *         photo_url: "https://toretti.family/people/brian.jpg"
 *     }
 */
export interface UserRequest {
    /** The user's first name. */
    first_name: string;
    /** The user's last name. */
    last_name?: string;
    /** Set of key-value pairs that will be stored with the user. */
    metadata?: Record<string, unknown>;
    /** URL of a photo to be used as the user's avatar. */
    photo_url?: string;
}
