/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the phone number is local or toll-free
 */
export type CreatePhoneNumberRequestType = "local" | "toll_free";
export const CreatePhoneNumberRequestType = {
    Local: "local",
    TollFree: "toll_free",
} as const;
