/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Splitit from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Users {
    interface Options {
        environment?: core.Supplier<environments.SplititEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        /** Override the Surge-Account header */
        surgeAccount?: core.Supplier<string | undefined>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the Surge-Account header */
        surgeAccount?: string | undefined;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Users {
    constructor(protected readonly _options: Users.Options) {}

    /**
     * Creates a new User object.
     *
     * @param {Splitit.UserRequest} request
     * @param {Users.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.users.create({
     *         first_name: "Brian",
     *         last_name: "O'Conner",
     *         metadata: {
     *             "email": "boconner@toretti.family",
     *             "user_id": 1234
     *         },
     *         photo_url: "https://toretti.family/people/brian.jpg"
     *     })
     */
    public create(
        request: Splitit.UserRequest,
        requestOptions?: Users.RequestOptions
    ): core.APIPromise<Splitit.UserResponse> {
        return core.APIPromise.from(
            (async () => {
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ?? environments.SplititEnvironment.Default,
                        "users"
                    ),
                    method: "POST",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        "Surge-Account":
                            (await core.Supplier.get(this._options.surgeAccount)) != null
                                ? await core.Supplier.get(this._options.surgeAccount)
                                : undefined,
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "surge",
                        "X-Fern-SDK-Version": "0.24.7",
                        "User-Agent": "surge/0.24.7",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    body: request,
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: _response.body as Splitit.UserResponse,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.SplititError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.SplititError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.SplititTimeoutError("Timeout exceeded when calling POST /users.");
                    case "unknown":
                        throw new errors.SplititError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * Retrieves a User object.
     *
     * @param {string} id -
     * @param {Users.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.users.show("usr_01j9dwavghe1ttppewekjjkfrx")
     */
    public show(id: string, requestOptions?: Users.RequestOptions): core.APIPromise<Splitit.UserResponse> {
        return core.APIPromise.from(
            (async () => {
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ?? environments.SplititEnvironment.Default,
                        `users/${encodeURIComponent(id)}`
                    ),
                    method: "GET",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        "Surge-Account":
                            (await core.Supplier.get(this._options.surgeAccount)) != null
                                ? await core.Supplier.get(this._options.surgeAccount)
                                : undefined,
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "surge",
                        "X-Fern-SDK-Version": "0.24.7",
                        "User-Agent": "surge/0.24.7",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: _response.body as Splitit.UserResponse,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.SplititError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.SplititError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.SplititTimeoutError("Timeout exceeded when calling GET /users/{id}.");
                    case "unknown":
                        throw new errors.SplititError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
